customhost = "employee.cbcoa8k4acwy.ap-south-1.rds.amazonaws.com"
customuser = "rdsuser"
custompass = "rdsuser1234"
customdb = "employee"
custombucket = "s3employeetechedge"
customregion = "ap-south-1"
